### PR TITLE
[middleware/sqhttp] responseWriterImpl must implement the http.Flusher interface

### PR DESCRIPTION
**Pull request by lbcjbb**
Without these modifications, the middleware could not be used on a stream endpoint.

### CODE REVIEW

**Comment by Julio-Guerra** [comment]
Thanks @lbcjbb 
Indeed we are currently hiding optional interfaces of the response writer.

My only problem with this classic solution is when the wrapped response writer does not implement the Flusher interface. This can have side effects I'd like to avoid. So I was instead thinking of having multiple response writer structures each having a given implementation combination - basically something like:

```go
var responseWriter http.ResponseWriter := responseWriterImpl{w}
if flusher, ok := w.(http.Flusher); ok {
  responseWriter = responseWriterFlusherImpl{responseWriter}
}
```

I guess it's easy to do for now with `http.Flusher` only, but it otherwise sounds like a code-generation candidate if there's a lot of optional interfaces.

I'll have a closer look to this in the next few weeks :pray:

**Comment by krostar** [comment]
Hi, 

[Some years ago I ran into the same issue](https://github.com/krostar/httpinfo), and found that any wrapper around http.ResponseWriter that use this kind of mechanism are inevitably restricting the usage of the wrapper to only simple cases

```go
type responseWriterWrapper struct{
    writer http.ResponseWriter
}

// implements ResponseWriter in responseWriterWrapper explicitly
```
This way of doing should be avoided as it breaks all previous implementation of the http.ResponseWriter that expect a method to be defined later.

The suggestion here

```go
type responseWriterWrapper struct{
    http.ResponseWriter
}

// add any method to responseWriterWrapper like Flush
```
may also be too naive, as it can add unwanted behavior in others implementation because the method will always be defined, but has the advantage of keeping all methods that are not explicit in http.ResponseWriter (like flush, or any custom ones) (as [gin](https://github.com/gin-gonic/gin/blob/094f9a9105f8e7b971a01a64677eef5a1f7bcd9b/response_writer.go#L46) did it).

The solution that I used at that time was inspired by a big project I don't remember of, and consist of having the original ResponseWriter in an attribute in the wrapper and [re-create all possible standard interface](https://github.com/krostar/httpinfo/blob/master/wrapper.go#L6). After a quick search it looks like some big company/projects also care about this problem and fixed it more or less the same way, as of [opencencus](https://github.com/census-instrumentation/opencensus-go/blob/f58a71790be543eb35437f28370e9817b5d092bb/plugin/ochttp/server.go#L230), [ovh](https://github.com/ovh/cds/blob/4c61fa7bc392c25cd5d09b1993d82911bc8d3a9a/engine/api/router_metrics.go#L171), [zipkin](https://github.com/openzipkin/zipkin-go/blob/c1d1eb59c8f7f8f8bd32cb30cb72e6e9343844b1/middleware/http/server.go#L195).

All those implementation (including the one I did few years ago), as they do not embed but keep the original interface as an attribute, have the problem of possibly limiting all other wraps at one point in time because any custom methods that any wraps of ResponseWriter define will be lost.

In my opinion the smarter wraps that exists around http.ResponseWriter are the one that embed the original one, as they keep it intact, and if they need a custom behavior on for instance the Flush method, they add it only if the flush method was defined at the beginning.

This is the case in those implementation of wrapper: [chi](https://github.com/go-chi/chi/blob/master/middleware/wrap_writer.go#L15), [datadog](https://github.com/DataDog/dd-trace-go/blob/02f0449efa3cb382d499fadc873957385dcb2192/contrib/internal/httputil/trace_gen.go#L23), [lyft](https://github.com/lyft/gostats/blob/942830ddf2d582e8732604823dbb162adc65ae56/stat_handler_wrapper.go#L7).

For information, the implementation mapping of datadog was made using [this tool](https://github.com/DataDog/dd-trace-go/blob/02f0449efa3cb382d499fadc873957385dcb2192/contrib/internal/httputil/make_responsewriter.go).

I hope this help,
krostar

**Comment by Julio-Guerra** [comment]
> All those implementation (including the one I did few years ago), as they do not embed but keep the original interface as an attribute, have the problem of possibly limiting all other wraps at one point in time because any custom methods that any wraps of ResponseWriter define will be lost.
> 
> In my opinion the smarter wraps that exists around http.ResponseWriter are the one that embed the original one, as they keep it intact, and if they need a custom behavior on for instance the Flush method, they add it only if the flush method was defined at the beginning.

Yes, I agree. And now that I see an example, I definitely think it's a code-generation candidate :laughing:
We are facing Go language limitations here, so there will be no perfect solution anyway, other than fixing it this way locally at our package-level...

Thanks a lot for the hints :pray:

**Comment by Julio-Guerra** [comment]
On it today. I noticed that I can some cases, I can avoid the wrapper Looks like I can avoid the response writer

**Comment by Julio-Guerra** [comment]
@lbcjbb #170 should do the job if you want to give it a try. I still need to do a proper validation with my actual Go test app ^^

**Comment by lbcjbb** [comment]
Thank you very much !

**Comment by Julio-Guerra** [comment]
Re-implemented by #170 and released early next week.
Thank you everyone for your help.

**Pull request closed without merging**
